### ISSUE TITLE
add json lib to wrap db

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/wrapweb#10]
I'm trying to add json lib to wrap db, since I don't have permissions to push repo, I can't add it. The releases page even contains MD5 sums.

Here's the original repo - https://github.com/nlohmann/json
Here are the releases - https://github.com/nlohmann/json/releases
Latest release zip - https://github.com/nlohmann/json/archive/v2.0.2.zip

There's nothing to build or do, the meson.build file would only contain - 

```
project('json', 'cpp', version : '2.0.2',
		default_options : ['cpp_std=c++11'])

inc = include_directories('src')
```

That's it.

It would be very helpful if you could add the following lib to wrap db.

**Comment by jpakkane** [comment]
Repository and branch created. You can now do the merge request, but please create a dep with `declare_dependency` so usage is consistent with other subprojects. Thanks.

**Comment by agauniyal** [comment]
@jpakkane can declare_dependency omit link_with param, since it is a header only lib.

**Comment by agauniyal** [comment]
So does that mean if I use declare dependency in original subproject, this would code - 

```
uWS_dep = dependency('uWS', required : false)
if uWS_dep.found()
  uWS_inc = []
  uWS_lib = []
else
  uWS_sp = subproject('uWS')
  uWS_inc = uWS_sp.get_variable('inc')
  uWS_lib = uWS_sp.get_variable('uWSlib')
endif
```

should get reduced to -

```
uWS_dep = dependency('uWS', required : false)
if uWS_dep.found()
else
  uWS_sp = subproject('uWS')
endif
```

**Comment by agauniyal** [comment]
And how is `source_hash` calculated?
