### ISSUE TITLE
New wrap: plog

### ISSUE THREAD

**Issue by inglor** [mesonbuild/wrapweb#101]
Please add new wrap for [plog] version [1.1.4]. Project is not meson so it will a patch 
[libplog-meson.tar.gz](https://github.com/mesonbuild/wrapweb/files/3405707/libplog-meson.tar.gz)

[plog]: https://github.com/SergiusTheBest/plog/
[1.1.4]: https://github.com/SergiusTheBest/plog/releases/tag/1.1.4

**Comment by sarum9in** [comment]
plog is ambiguous, see https://en.wikipedia.org/wiki/Plog, especially "plog, a Unix command related to the Point-to-Point Protocol daemon", I suggest the name `sergiusthebest-plog`. What do you think?

**Comment by inglor** [comment]
Sure this name will do, thanks.

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/sergiusthebest-plog
