### ISSUE TITLE
New wrap: lz4

### ISSUE THREAD

**Issue by jcaesar** [mesonbuild/wrapweb#103]
Version: 1.9.1
License: BSD 2-clause 
Url: https://github.com/lz4/lz4/
Name: lz4

Preview: https://github.com/jcaesar/crappywraps/tree/master/lz4

**Comment by jcaesar** [comment]
Argh. I just realized, lz4 already [contains a meson build file](https://github.com/lz4/lz4/blob/40bd6164bb7b077aa37d8617e8dcf3664fb7c57a/contrib/meson/lib/meson.build), and the one I've written is entirely unnecessary.

Now I'm unsure what to do.

**Comment by jcaesar** [comment]
@sarum9in any comments?

**Comment by sarum9in** [comment]
What about adding a root `meson.build` file and importing this file from it via `subdir()`?

https://mesonbuild.com/Reference-manual.html#subdir

**Comment by jcaesar** [comment]
Any neat way of dealing with the options file, which is also in a subdirectory? (If in doubt, I can duplicate it.)

**Comment by sarum9in** [comment]
I don't have any good ideas. We should implement subdir option as was suggested I suppose. Let's just copy it for now.

**Comment by jcaesar** [comment]
To get this finally done…

https://github.com/jcaesar/crappywraps/blob/master/lz4/lz4.wrap

I've also received permission to move the meson build files to a different folder upstream, so for future releases of lz4, only a single meson.build and meson_options.txt are required.

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/lz4
