### ISSUE TITLE
New wrap: hedley

### ISSUE THREAD

**Issue by mattyclarkson** [mesonbuild/wrapweb#107]
upstream url: https://github.com/nemequ/hedley
version: 9

Have put up a repo at: https://github.com/mattyclarkson/hedley

**Comment by sarum9in** [comment]
This name seems a little ambiguous, will `nemequ-hedley` work?

**Comment by mattyclarkson** [comment]
It would, but  what happens if it ever moves to a shared org? Similar to the catch/catch2 rename? I don't particularly mind but hedley seems pretty unique nothing else comes up in a Google search for `c c++ hedley`

**Comment by mattyclarkson** [comment]
Bump

**Comment by sarum9in** [comment]
Sorry for the delay in my response.
I don't have a good answer here. Unfortunately the policy is not strict enough to handle these cases well. If the name is ambiguous I would go for `owner-name`, if name is widely recognized I go for `name`. I think `c++ hedley` search is reasonable as the context is important. So I am creating https://github.com/mesonbuild/hedley.
I created branch 10 as it is the latest version available at the moment.
