### ISSUE TITLE
New wraps: nonstd-{any,byte,expected,observer-ptr,optional,span,status-value,string-view}

### ISSUE THREAD

**Issue by mattyclarkson** [mesonbuild/wrapweb#108]
Upstream projects:
  - https://github.com/martinmoene/any-lite
  - https://github.com/martinmoene/byte-lite
  - https://github.com/martinmoene/expected-lite
  - https://github.com/martinmoene/observer-ptr-lite
  - https://github.com/martinmoene/optional-lite
  - https://github.com/martinmoene/span-lite
  - https://github.com/martinmoene/status-value-lite
  - https://github.com/martinmoene/string-view-lite

These are individual future compatability headers for C++.

Having a `nonstd-<header>-lite` wrap would be really useful for these projects.

**Comment by sarum9in** [comment]
It seems every package is named like
```cmake
set( unit_name       "any" )
set( package_name    "${unit_name}-lite" )
```

Each individual name looks unique enough so I am happy to create
- https://github.com/mesonbuild/nonstd-any-lite
- https://github.com/mesonbuild/nonstd-byte-lite
- https://github.com/mesonbuild/nonstd-expected-lite
- https://github.com/mesonbuild/nonstd-observer-ptr-lite
- https://github.com/mesonbuild/nonstd-optional-lite
- https://github.com/mesonbuild/nonstd-span-lite
- https://github.com/mesonbuild/nonstd-status-value-lite
- https://github.com/mesonbuild/nonstd-string-view-lite
