### ISSUE TITLE
Let's Encrypt certificate has expired

### ISSUE THREAD

**Issue by meisenzahl** [mesonbuild/wrapweb#111]
It seems that your Let's Encrypt certificate for [wrapdb.mesonbuild.com](https://wrapdb.mesonbuild.com/) has expired. Because you use `HSTS` a downgrade to `HTTP` is not possible. This means that `wrapdb` cannot currently be used.

**Comment by sarum9in** [comment]
@ignatenkobrain could you please take a look?

**Comment by Simske** [comment]
Mesonbuild has a fallback to HTTP, which is not working.
Until the certificate is renewed, this can be fixed by not verifying the certificate, see Pull Request on meson: https://github.com/mesonbuild/meson/pull/6029

**Comment by sarum9in** [comment]
Seems this was resolved.
