### ISSUE TITLE
I'm trying to add cpr to wrapdb

### ISSUE THREAD

**Issue by riemass** [mesonbuild/wrapweb#15]
Hello, 
I'm trying to add cpr to wrapdb. Can you make a repo so I can fork it and push the changes.

Library: https://github.com/whoshuu/cpr
Fork with meson.build that I currenty include in my project: https://github.com/riemass/cpr
Something I created on my local account for test: https://github.com/riemass/cpr-meson-wrap

Also, before pushing to your repo I'm planning on adding version and licence information to meson.build files.

**Comment by jpakkane** [comment]
Which version are you planning on wrapping? Must be an official release, as wrapdb does not support "git head" releases or the like.

**Comment by riemass** [comment]
I've succeeded in wrapping the 1.3.0 version of the project, as that is the most recent tagged version.

**Comment by jpakkane** [comment]
Thanks, created.
