### ISSUE TITLE
New wrap for pcre2

### ISSUE THREAD

**Issue by zeehio** [mesonbuild/wrapweb#16]
I built a wrap for pcre2. I used a new repository (not based on https://github.com/mesonbuild/pcre/tree/8.37) because pcre2 has a revised API and it is considered a different package in most linux distributions. 

From http://mesonbuild.com/Wrap-review-guidelines.html I see I need to submit a merge request, but I don't know where should I submit it, as it is a new repository: https://github.com/zeehio/pcre2

Thanks for your time

- [x] project() has version string
- [x] project() has license string
- [x] if new project, master has tagged commit as only commit
- [x] if new branch, it is branched from master
- [x] contains a readme.txt
- [x] contains an upstream.wrap file
- [x] download link points to authoritative upstream location
- [x] wrap repository contains only build system files
- [ ] merge request is pointed to correct target branch (not master)
- [x] wrap works
- [x] repo does not have useless top level directory (i.e. libfoobar-1.0.0)

**Comment by jpakkane** [comment]
I created [a PCRE2 repository](https://github.com/mesonbuild/pcre2). Please create a MR against that one with your changes. Thanks.
