### ISSUE TITLE
new wrap: zstd

### ISSUE THREAD

**Issue by shawnl** [mesonbuild/wrapweb#18]
https://github.com/shawnl/zstd-wrap/tree/1.3.3

while upstream has some meson files in contrib/build meson unfortunately does not work with them (although I based my work off them, and fixed the build upstream, which was released with 1.3.3)

- [X] project() has version string
- [X] project() has license string
- [X] if new project, master has tagged commit as only commit
- [X] if new branch, it is branched from master
- [X] contains a readme.txt
- [X] contains an upstream.wrap file
- [X] download link points to authoritative upstream location
- [X] wrap repository contains only build system files
- [ ] merge request is pointed to correct target branch (not master)
- [X] wrap works
- [X] repo does not have useless top level directory (i.e. libfoobar-1.0.0)

**Comment by jpakkane** [comment]
Repo and branch [created here](https://github.com/mesonbuild/zstd/tree/1.3.3). Thanks.
