### ISSUE TITLE
New wrap: pcg-cpp

### ISSUE THREAD

**Issue by talisein** [mesonbuild/wrapweb#20]
Hi, I created a wrap for the PCG random number generator library (it is a header-only library) at https://github.com/talisein/pcg-cpp-wrap

I also made the 0.98.1 branch on that repo. Thanks.

**Comment by jpakkane** [comment]
Thanks. I've created the repos. Due to complicated reasons you'll need to branch from that, add your files in a separate commit and then file a MR. This is needed so the background code can do its magic.
