### ISSUE TITLE
Web api for querying newest revision for a branch

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/wrapweb#3]
We want to call into the web service specifying a project and branch. The return value is the largest available revision number.

This will be used to easily test from the command line client whether the current revision of a project is the newest one.

**Comment by ignatenkobrain** [comment]
should it be in `/projects/<project>` or it should be in separate `/projects/<project>/get_latest` or something like this?

**Comment by jpakkane** [comment]
Overloading `/projects/<project>/something` seems a bit wonky. It seems bug-prone to have different services in the same prefix and then doing different types of operations depending on the path.

Maybe it would be better to put all queries that are used on the command line client to its own prefix. Something like `/v1/cliquery/get_latest/libpng/1.6`.

**Comment by ignatenkobrain** [comment]
`/v1/query/get_latest/libpng` will return `{output: ok, version: 1.6, branch: 2}'
`/v1/query/get_latest/libpng/1.6` will return `{output: ok, branch: 2}'

How about this?

**Comment by jpakkane** [comment]
lgtm but instead of "version" have "branch" and instead of "branch" have "revision".
