### ISSUE TITLE
new wrap: date

### ISSUE THREAD

**Issue by barcharcraz** [mesonbuild/wrapweb#48]
I'm wrapping https://github.com/HowardHinnant/date, not sure what the repo should be called, maybe hhdate

**Comment by sarum9in** [comment]
After small discussion on IRC __tim suggested `hinnant-date` as the name based on the presentation filename. What do you think?

**Comment by barcharcraz** [comment]
Yeah that sounds good to me.

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/hinnant-date branch 2.4.1
