### ISSUE TITLE
New wrap: range-v3

### ISSUE THREAD

**Issue by barsoosayque** [mesonbuild/wrapweb#51]
I wrote a wrap file for the [range-v3][1] library. Wanna share it via _Wrap DB_. However, there are two minor issues:
- Is it correct name for the library ? The other option to name it, I think, would be just "range", and then make a "third" revision, [like the way the catch2 wrap exist][2].
- [As stated here][3], _range-v3_ library contains some mixed licenses: Boost License, libc++ License, license from the book "Elements of Programming" and SGI C++ Standard Template Library License. How to handle it in the wrap file ?

[1]: https://github.com/ericniebler/range-v3/
[2]: https://wrapdb.mesonbuild.com/catch
[3]: https://github.com/ericniebler/range-v3#license

**Comment by jpakkane** [comment]
For the `project()` call, the license argument is only a string. Meson does not parse it, or try to enforce any license compatibility or anything of the sort. You can set it to any string that describes the license. As a random example you could set it to `gpl2,lpgl2.1` for a project that is dual licensed under GPL2 and LPGL2.1.

**Comment by sarum9in** [comment]
As for the library name `range-v3` seems to be searchable name of this library, so I think it's fine to name it like this.

https://github.com/mesonbuild/range-v3
