### ISSUE TITLE
new wrap: bdwgc

### ISSUE THREAD

**Issue by barcharcraz** [mesonbuild/wrapweb#63]
I have a simple wrap for the single threaded non-parallel build of bdwgc.

**Comment by sarum9in** [comment]
Could you please clarify if this is https://github.com/ivmai/bdwgc? Or what is the main page of the project?

**Comment by barcharcraz** [comment]
Yes that page is the main page as far as I can tell

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/bdwgc
