### ISSUE TITLE
new wrap: chipmunk

### ISSUE THREAD

**Issue by jhasse** [mesonbuild/wrapweb#67]
I've created a warp and meson.build for https://github.com/slembcke/Chipmunk2D. While it's named Chipmunk2D there, I think the name should be chipmunk, as Fedora calls its package `chipmunk-devel` for example. I couldn't find a pkg-config file.

**Comment by sarum9in** [comment]
They call the project `chipmunk` https://github.com/slembcke/Chipmunk2D/blob/master/CMakeLists.txt#L3
So this looks reasonable for me.
https://github.com/mesonbuild/chipmunk/tree/7.0.2 is up

**Comment by jhasse** [comment]
Can you create the branch 6.2.2? Version 7 still hasn't implemented some features I need.

**Comment by sarum9in** [comment]
Done.
