### ISSUE TITLE
Wrap file for jsoncpp

### ISSUE THREAD

**Issue by koponomarenko** [mesonbuild/wrapweb#68]
Hey guys! I created a wrap file for `jsoncpp` lib, which already supports Meson. 
Following the instructions, I also created a repository: https://github.com/koponomarenko/jsoncpp . How can I transfer it to mesonbuild?

**Comment by koponomarenko** [comment]
- [*] project() has version string
- [*] project() has license string
- [*] if new project, master has tagged commit as only commit
- [*] if new branch, it is branched from master
- [*] contains a readme.txt
- [*] contains an upstream.wrap file
- [*] download link points to authoritative upstream location
- [ ] wrap repository contains only build system files
- [ ] merge request is pointed to correct target branch (not master)
- [*] wrap works
- [*] repo does not have useless top level directory (i.e. libfoobar-1.0.0)

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/jsoncpp is up, please create a PR targeting branch 1.8.4.
