### ISSUE TITLE
nlohmann_json: duplication and heavy tarball

### ISSUE THREAD

**Issue by mpoquet** [mesonbuild/wrapweb#76]
Hello,

I am a new Meson user and I would like to add a wrap for the [nlohmann/json](https://github.com/nlohmann/json) library.

### Duplication
I saw that the library is already wrapped under the ``json`` name [there on Wrap DB](https://wrapdb.mesonbuild.com/json) but also under the ``nlohmann_json`` name [there on Wrap DB](https://wrapdb.mesonbuild.com/nlohmann_json). Is this intentional?

### Downloaded files are a thousand time heavier than needed
The wraps of the two existing repos download the full source tarball of **110 MB**, which could be avoided since the project maintainer provides an includable tarball of ~130 KB.

I successfully could retrieve the [latest release include zip] and apply [this (standard) patch] to get a [Nix package] of the library (by calling Meson).

[latest release include zip]: https://github.com/nlohmann/json/releases/download/v3.4.0/include.zip
[this (standard) patch]: https://github.com/netorcai/pkgs/blob/f31f97a394d3fa8c8da69ab0074acc9105e8d606/nlohmann_json/add-meson.patch
[Nix package]: https://github.com/netorcai/pkgs/blob/f31f97a394d3fa8c8da69ab0074acc9105e8d606/nlohmann_json/default.nix

**Comment by sarum9in** [comment]
> Duplication

The `json` package has a comment in the description `deprecated: use nlohmann_json`. It was poorly named and kept for backward compatibility.

> The wraps of the two existing repos download the full source tarball of 110 MB, which could be avoided since the project maintainer provides an includable tarball of ~130 KB.

That is up for maintainers. Patches are welcome, I have no idea about individual wraps. You can check pull request history to find wrap maintainers.

**Comment by mpoquet** [comment]
Thanks for the quick reply!

I submitted a pull request to mesonbuild/nlohmann_json [there](https://github.com/mesonbuild/nlohmann_json/pull/2).

**Comment by sarum9in** [comment]
Thank you. Just FYI I get notification for all pull requests and new issues in all wrap repositories. :)
