### ISSUE TITLE
new wrap: benchmark

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/wrapweb#78]
upstream url: https://github.com/google/benchmark
version: 1.4.1

**Comment by dcbaker** [comment]
Since we call "google test" "gtest", maybe it makes sense to call this "gbenchmark"? Just a though.

**Comment by jeandet** [comment]
@sarum9in  @dcbaker  google test is not named just Test but googletest or gtest while benchmark is never named upstream google benchmark or gbenchmark, so I don't know what is better.
Benchmark is a shitty name...(funny for a company who knows search engines)

**Comment by jpakkane** [comment]
> funny for a company who knows search engines

Would that be the same company who created a programming language named "Go"? :P

**Comment by sarum9in** [comment]
I think we should make it as a policy for wraps to not introduce generic names for these cases and use google-benchmark, similar to https://github.com/mesonbuild/microsoft-gsl

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/google-benchmark
