### ISSUE TITLE
new wrap: mocklibc

### ISSUE THREAD

**Issue by inigomartinez** [mesonbuild/wrapweb#81]
New wrap for mocklibc-1.0: https://code.google.com/archive/p/mocklibc/

They don't have an upstream url as it's not maintained anymore.

last stable release: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mocklibc/mocklibc-1.0.tar.gz
version: 1.0

**Comment by inigomartinez** [comment]
This wrap file is already in use in [polkit](https://gitlab.freedesktop.org/polkit/polkit/merge_requests/2/diffs?commit_id=3440b691f163815006653ef6093a9108a16817bc).

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/mocklibc
