### ISSUE TITLE
new wrap: re2

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/wrapweb#83]
upstream url: https://github.com/google/re2
version : 2019-03-01

**Comment by sarum9in** [comment]
What do you think about the name? `google-re2`? Or is it widely known as just `re2`?

**Comment by koponomarenko** [comment]
Looks like this is widely known as just `re2`:
https://packages.debian.org/source/sid/re2
https://www.archlinux.org/packages/extra/x86_64/re2/

**Comment by jpakkane** [comment]
That is also its [pkg-config name](https://packages.debian.org/search?searchon=contents&keywords=re2.pc&mode=path&suite=unstable&arch=any).

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/re2

thanks for comments :)
