### ISSUE TITLE
new wrap: mpack

### ISSUE THREAD

**Issue by dirkson** [mesonbuild/wrapweb#84]
upstream url: https://github.com/ludocode/mpack
version: 1.0

pkg-config name is also mpack

**Comment by sarum9in** [comment]
I am not sure `mpack` is an appropriate name as there are other projects named `mpack` such as https://en.wikipedia.org/wiki/Mpack_(Unix) that come first.

I propose to name it `ludocode-mpack`. Any objections?

**Comment by dirkson** [comment]
Since most people will use wrabdb for libraries, rather than tool bundles (like the older mpack), I'm not sure we need to be concerned about this name collision.

That said, most distros appear to have solved this collision by naming ludocode's mpack "libmpack". That seems like a slightly cleaner solution to me, even if it doesn't match the pkg-config name.

**Comment by sarum9in** [comment]
There is also https://en.wikipedia.org/wiki/MPack_(software)
libmpack doesn't work since there is https://github.com/libmpack/libmpack

Sorry, I think I am going to stick with `ludocode-mpack`, other options are too ambiguous.

**Comment by dirkson** [comment]
Good call; I didn't even notice the other msgpack-based mpack.
