### ISSUE TITLE
new wrap: FakeIt

### ISSUE THREAD

**Issue by jdemilledt** [mesonbuild/wrapweb#86]
upstream url: https://github.com/eranpeer/FakeIt
version: 2.0.5

**Comment by sarum9in** [comment]
https://fake-it.ws/
https://github.com/eranpeer/FakeIt
https://github.com/bentonam/fakeit
https://www.npmjs.com/package/fakeit points to a different project also

I find `fakeit` name ambiguous so I propose `eranpeer-fakeit` consistent with other ambiguous cases. Any objections?

**Comment by jdemilledt** [comment]
No objections.

**Comment by sarum9in** [comment]
http://github.com/mesonbuild/eranpeer-fakeit

apologies for the delay.
