### ISSUE TITLE
new wrap: libcrc

### ISSUE THREAD

**Issue by ssloboda** [mesonbuild/wrapweb#87]
upstream url: https://github.com/lammertb/libcrc
version: 2.0.0

**Comment by sarum9in** [comment]
I propose the name `lammertb-libcrc`. It doesn't look that this library is widely used?
Also there is libcrc32c kernel module which looks pretty similar... Any objections?

P.S. Sorry for slow response, this slipped.

**Comment by ssloboda** [comment]
`lammertb-libcrc` seems fine to me. The target platform is bare-metal so no kernel modules available.

**Comment by sarum9in** [comment]
I just meant that the name `libcrc` is ambiguous.

https://github.com/mesonbuild/lammertb-libcrc is up and ready for pull requests :)

**Comment by ssloboda** [comment]
Awesome thank you - I'll try to get a PR up for that this weekend
