### ISSUE TITLE
new wrap: json-c

### ISSUE THREAD

**Issue by ascent12** [mesonbuild/wrapweb#91]
Upstream URL: https://github.com/json-c/json-c
Version: 0.13.1

https://github.com/ascent12/json-c/tree/0.13.1

**Comment by sarum9in** [comment]
https://github.com/json-c/json-c/blob/3e81b4abe359c8128bb2b4127f4e8c8c057fb004/json-c.pc.in

`json-c` is the pkgbuild name as far as I understand.

https://github.com/mesonbuild/json-c
