### ISSUE TITLE
update: catch2 version 2.7.2

### ISSUE THREAD

**Issue by vedranmiletic** [mesonbuild/wrapweb#92]
```
[wrap-file]
directory = Catch2-2.7.2

source_url = https://github.com/catchorg/Catch2/archive/v2.7.2.zip
source_filename = Catch2-2.7.2.zip
source_hash = 7edd16ed7c9c6725f14e1ae997431a69835a5f9ac1dc90dc8ec1548bd5e0fe02
```

Just a minor style fix as well, added newline after `directory` and removed newline after `source_hash`.

**Comment by vedranmiletic** [comment]
I also made the changes here (both branch and tag): https://github.com/vedranmiletic/catch2/tree/2.7.2

**Comment by sarum9in** [comment]
I have created a branch `2.7.2`. Please in the future just create a pull request in the corresponding repository. If the branch doesn't exist I can create the branch later and point PR to the new branch.

**Comment by vedranmiletic** [comment]
Thanks! Will do.

**Comment by vedranmiletic** [comment]
I see branch 2.7.2 is even with master in the [repo](https://github.com/mesonbuild/catch2/tree/2.7.2) and 2.7.2 isn't listed on [WrapDB](https://wrapdb.mesonbuild.com/catch2). Is that expected? Do I need to wait a little more?

**Comment by jpakkane** [comment]
The release goes to wrapdb when the MR adding the code is merged. So go ahead and file your MR, once it is merged it will get to the wrapdb web site.

**Comment by vedranmiletic** [comment]
Thanks, I think I did it correctly both for this and #93.
