### ISSUE TITLE
new wrap: clara

### ISSUE THREAD

**Issue by vedranmiletic** [mesonbuild/wrapweb#96]
https://github.com/catchorg/Clara

Can we go with the name `clara` just like we have `catch` and `catch2` or is it ambiguous?

**Comment by sarum9in** [comment]
I mean simple googling gives me https://claraweb.jlab.org/clara/docs/quickstart/cpp.html
which is probably a different thing?
So I am afraid it's ambiguous... :(

**Comment by vedranmiletic** [comment]
Then catch-clara or catchorg-clara? The second one is more in line with other packages.

**Comment by sarum9in** [comment]
http://github.com/mesonbuild/catchorg-clara yup, sounds good.
