### ISSUE TITLE
new wrap: BigInteger

### ISSUE THREAD

**Issue by MichaelBelousov** [mesonbuild/wrapweb#97]
Public domain library with the source found here:
[https://mattmccutchen.net/bigint/](https://mattmccutchen.net/bigint/)

**Comment by sarum9in** [comment]
Not sure about the name, what do you think about `mattmccutchen-bigint`?

**Comment by MichaelBelousov** [comment]
Sounds appropriate to me.

**Comment by sarum9in** [comment]
https://github.com/mesonbuild/mattmccutchen-bigint
